spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sellsystem?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

logging:
  level:
    org.springframework.security: DEBUG
    com.project.dao.impl: DEBUG
    org.springframework.jdbc.core: DEBUG

mybatis:
  mapper-locations: classpath:mapper/*.xml  # XML 扫描路径
  configuration:  # 固定层级
    map-underscore-to-camel-case: true  # 驼峰映射
